<?xml version="1.0" encoding="utf-8"?>

<!-- Lvs.xml | Author: Ebrahim Gulamali (c3264525) Date created: 16/10/21 -->
<?xml-stylesheet type="text/xsl" href="xslt.xsl"?>
<?xml-stylesheet href="xslt.xsl" type="type/xsl"?>
<!DOCTYPE Jimscars [
<!ELEMENT Jimscars (Vehicle+)>
<!ELEMENT Vehicle (category, model, description, cost, year, URL, make, pictures+, colour, enginesize, dealer, safteyrating, couponcode?, reviews+)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT cost (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT URL (#PCDATA)>
<!ELEMENT make (#PCDATA)>
<!ELEMENT pictures (images)>
<!ELEMENT images EMPTY>
<!ATTLIST images src CDATA #REQUIRED>
<!ATTLIST images height CDATA #REQUIRED>
<!ATTLIST images width CDATA #REQUIRED>
<!ELEMENT colour (#PCDATA)>
<!ELEMENT enginesize (#PCDATA)>
<!ELEMENT dealer (#PCDATA)>
<!ELEMENT safteyrating (#PCDATA)>
<!ELEMENT couponcode (#PCDATA)>
<!ELEMENT reviews (#PCDATA)>
<!ENTITY ev "Electric Vehicle">
<!ENTITY L "Litres">
]>
<Jimscars>
	<Vehicle>
		<category>Luxury</category>
		<model>Urus</model>
		<description>Lamborghini Urus is the first Super Sport Utility Vehicle in the world to merge the soul of a super sports car with the functionality of an SUV. Powered by a 4.0-liter twin-turbo V8 engine producing 650 CV and 850 Nm of torque, Urus accelerates from 0 to 62 mph in 3.6 seconds and reaches a top speed of 190 mph. The design, performance, driving dynamics and driving emotion flow effortlessly into this visionary approach to Lamborghini DNA.</description>
		<cost>300000</cost>
		<year>2020</year>
		<make>Lambhorghini</make>
		<pictures>
			<images src="images/1.jpg" height="700" width="540"/>
		</pictures>
		<colour>Yellow</colour>
		<enginesize>600</enginesize>
		<URL>https://www.lamborghini.com/en-en/models/urus/urus</URL>
		<dealer>Lambhorghini</dealer>
		<safteyrating>3</safteyrating>
		<couponcode></couponcode>
		<reviews>Best SUV ever!</reviews>
	</Vehicle>
	<Vehicle>
		<category>Luxury</category>
		<model>Adventador</model>
		<description>Revolutionary thinking is at the heart of every idea from Automobili Lamborghini. Whether it is aerospace-inspired design or technologies applied to the naturally aspirated V12 engine or carbon-fiber structure, going beyond accepted limits is part of our philosophy. The Aventador advances every concept of performance, immediately establishing itself as the benchmark for the super sports car sector. Giving a glimpse of the future today, it comes from a family of supercars already considered legendary.</description>
		<cost>200000</cost>
		<year>2019</year>
		<make>Lambhorghini</make>
		<pictures>
			<images src="images/4.jpg" height="700" width="540"/>
		</pictures>
		<colour>Red</colour>
		<enginesize>500</enginesize>
		<URL>https://www.lamborghini.com/en-en/models/aventador</URL>
		<dealer>Lambhorghini</dealer>
		<safteyrating>2</safteyrating>
		<couponcode></couponcode>
		<reviews>I bought this after Shiba inu coin prices peaked, and I love every second of it! Wayy better than catching the bus lol</reviews>
	</Vehicle>
	<Vehicle>
		<category>Luxury</category>
		<model>Huracane</model>
		<description>Discover all the new models of this exclusive car family, created to shape to your deepest emotions. Combining the highest expression of Lamborghini’s power with the exclusive refinement of Italian handicraft, this series embodies authentic design and state-of-the-art mechanical technology. The Lamborghini Huracán is the perfect fusion of technology and design. With its crisp, streamlined lines, designed to cut through the air and tame the road, you’ll get a thrill just by looking at it. The only thing better than taking in this beauty from a distance is actually touching it. The finest Italian craftsmanship lavished on finishes of unprecedented prestige and quality.</description>
		<cost>300000</cost>
		<year>2020</year>
		<make>Lambhorghini</make>
		<pictures>
			<images src="images/7.jpg" height="" width=""/>
		</pictures>
		<colour>Yellow</colour>
		<enginesize>600</enginesize>
		<URL>https://www.lamborghini.com/en-en/models/huracan</URL>
		<dealer>Lambhorghini</dealer>
		<safteyrating>3</safteyrating>
		<couponcode></couponcode>
		<reviews>Slatt!</reviews>
	</Vehicle>
</Jimscars>
